const mongoose = require('mongoose');
const Property = require('./models/Property');

// Replace this with your MongoDB connection string
const mongoURI = 'mongodb+srv://princy:Princy%402003@cluster0.bakhavs.mongodb.net/Rentify?retryWrites=true&w=majority';
mongoose.connect(mongoURI, {
  useNewUrlParser: true,
  useUnifiedTopology: true,
})
  .then(() => console.log('MongoDB connected'))
  .catch(err => console.log(err));

const sampleProperties = [
  {
    _id: '1',
    title: 'Sample Property 1',
    description: 'This is a sample property description.',
    price: 250000,
    location: 'New York, NY',
    bedrooms: 3,
    bathrooms: 2,
    hospitalsNearby: 'Hospital A, Hospital B',
    collegesNearby: 'University A, College B',
    likes: 10,
  },
  {
  _id: '2',
    title: 'Sample Property 2',
    description: 'Another sample property description.',
    price: 350000,
    location: 'Los Angeles, CA',
    bedrooms: 4,
    bathrooms: 3,
    hospitalsNearby: 'Hospital C, Hospital D',
    collegesNearby: 'University B, College C',
    likes: 15,
  },
  {
    _id: '3',
    title: 'Sample Property 3',
    description: 'This is a third sample property description.',
    price: 450000,
    location: 'Chicago, IL',
    bedrooms: 5,
    bathrooms: 4,
    hospitalsNearby: 'Hospital E, Hospital F',
    collegesNearby: 'University C, College D',
    likes: 8,
  },
  {
    _id: '4',
    title: 'Sample Property 4',
    description: 'Another sample property description.',
    price: 300000,
    location: 'San Francisco, CA',
    bedrooms: 3,
    bathrooms: 2,
    hospitalsNearby: 'Hospital G, Hospital H',
    collegesNearby: 'University D, College E',
    likes: 12,
  },
  {
    _id: '5',
    title: 'Sample Property 5',
    description: 'This is a fifth sample property description.',
    price: 400000,
    location: 'Boston, MA',
    bedrooms: 4,
    bathrooms: 3,
    hospitalsNearby: 'Hospital I, Hospital J',
    collegesNearby: 'University E, College F',
    likes: 7,
  },
  {
    _id: '6',
    title: 'Sample Property 6',
    description: 'Another sample property description.',
    price: 550000,
    location: 'Miami, FL',
    bedrooms: 5,
    bathrooms: 4,
    hospitalsNearby: 'Hospital K, Hospital L',
    collegesNearby: 'University F, College G',
    likes: 9,
  },
  {
    _id: '7',
    title: 'Sample Property 7',
    description: 'This is a seventh sample property description.',
    price: 275000,
    location: 'Seattle, WA',
    bedrooms: 3,
    bathrooms: 2,
    hospitalsNearby: 'Hospital M, Hospital N',
    collegesNearby: 'University G, College H',
    likes: 11,
  },
  {
    _id: '8',
    title: 'Sample Property 8',
    description: 'Another sample property description.',
    price: 425000,
    location: 'Atlanta, GA',
    bedrooms: 4,
    bathrooms: 3,
    hospitalsNearby: 'Hospital O, Hospital P',
    collegesNearby: 'University H, College I',
    likes: 6,
  },
  {
    _id: '9',
    title: 'Sample Property 9',
    description: 'This is a ninth sample property description.',
    price: 375000,
    location: 'Denver, CO',
    bedrooms: 4,
    bathrooms: 3,
    hospitalsNearby: 'Hospital Q, Hospital R',
    collegesNearby: 'University I, College J',
    likes: 14,
  },
  {
    _id: '10',
    title: 'Sample Property 10',
    description: 'Another sample property description.',
    price: 500000,
    location: 'Austin, TX',
    bedrooms: 5,
    bathrooms: 4,
    hospitalsNearby: 'Hospital S, Hospital T',
    collegesNearby: 'University J, College K',
    likes: 10,
  },
  {
    _id: '11',
    title: 'Sample Property 11',
    description: 'This is an eleventh sample property description.',
    price: 325000,
    location: 'Portland, OR',
    bedrooms: 3,
    bathrooms: 2,
    hospitalsNearby: 'Hospital U, Hospital V',
    collegesNearby: 'University K, College L',
    likes: 8,
  },
  {
    _id: '12',
    title: 'Sample Property 12',
    description: 'Another sample property description.',
    price: 475000,
    location: 'Washington, D.C.',
    bedrooms: 4,
    bathrooms: 3,
    hospitalsNearby: 'Hospital W, Hospital X',
    collegesNearby: 'University L, College M',
    likes: 13,
  },
  {
    _id: '13',
    title: 'Sample Property 13',
    description: 'This is a thirteenth sample property description.',
    price: 600000,
    location: 'San Diego, CA',
    bedrooms: 5,
    bathrooms: 4,
    hospitalsNearby: 'Hospital Y, Hospital Z',
    collegesNearby: 'University M, College N',
    likes: 11,
  },
  {
    _id: '14',
    title: 'Sample Property 14',
    description: 'Another sample property description.',
    price: 450000,
    location: 'Philadelphia, PA',
    bedrooms: 4,
    bathrooms: 3,
    hospitalsNearby: 'Hospital AA, Hospital BB',
    collegesNearby: 'University N, College O',
    likes: 9,
  },
  {
    _id: '15',
    title: 'Sample Property 15',
    description: 'This is a fifteenth sample property description.',
    price: 375000,
    location: 'Phoenix, AZ',
    bedrooms: 4,
    bathrooms: 3,
    hospitalsNearby: 'Hospital CC, Hospital DD',
    collegesNearby: 'University O, College P',
    likes: 12,
  },
  // Add the rest of your sample property data here
];

const seedDB = async () => {
  try {
    await Property.insertMany(sampleProperties);
    console.log('Properties added');
  } catch (err) {
    console.log(err);
  }
};

seedDB();
